; VictoriaOS: header file for stdcpy, strcmp and other functions
; Copyright Ilya Strukov, 2008

; This program is free software; you can redistribute it and/or modify
; it under the terms of the GNU General Public License as published by
; the Free Software Foundation; either version 2 of the License, or
; (at your option) any later version.

include 'memset.inc'
include 'string\strcpy.inc'
include 'string\strncpy.inc'
include 'string\strcmp.inc'
include 'string\strlen.inc'
include 'string\strtok.inc'
;-- vim: set filetype=fasm:
